fix: gracefully handle loadFull being called multiple times to prevent "TypeError: a.loadFull is not a function when rollbar loaded multiple times"
fixes #818